<a href="https://colab.research.google.com/github/satani99/fastai_22_2/blob/main/nn_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
from torch import tensor

In [4]:
def matmul(a, b):
  ar, ac = a.shape
  br, bc = b.shape
  assert ac==br
  c = torch.zeros(ar, bc)
  for i in range(ar):
    for j in range(bc):
      for k in range(ac): c[i,j] += a[i,k] * b[k,j]
  return c


In [5]:
m1 = torch.randn(5, 28*28)
m2 = torch.randn(784, 10)

In [6]:
%time t1 = matmul(m1, m2)

CPU times: user 1.56 s, sys: 2.41 ms, total: 1.56 s
Wall time: 1.66 s


In [7]:
 %timeit -n 20 t2=m1@m2

The slowest run took 185.53 times longer than the fastest. This could mean that an intermediate result is being cached.
164 µs ± 385 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [8]:
a = tensor([10., 6, -4])
b = tensor([2., 8, 7])
a + b

tensor([12., 14.,  3.])

In [9]:
a < b

tensor([False,  True,  True])

In [10]:
(a < b).all(), (a == b).all()

(tensor(False), tensor(False))

In [11]:
(a + b).mean().item()

9.666666984558105

In [13]:
m = tensor([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
m*m

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [14]:
def matmul(a, b):
  ar, ac = a.shape
  br, bc = b.shape
  assert ac==br
  c = torch.zeros(ar, bc)
  for i in range(ar):
    for j in range(bc):
      c[i,j] = (a[i] * b[:,j]).sum()
    return c

%timeit -n 20 t3 = matmul(m1, m2)

311 µs ± 161 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [15]:
a = tensor([10., 6, -4])
a > 0

tensor([ True,  True, False])

In [16]:
m = tensor([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
(m-5) / 2.73

tensor([[-1.4652, -1.0989, -0.7326],
        [-0.3663,  0.0000,  0.3663],
        [ 0.7326,  1.0989,  1.4652]])

In [17]:
c = tensor([10., 20, 30])
m = tensor([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
m.shape, c.shape

(torch.Size([3, 3]), torch.Size([3]))

In [18]:
m + c

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [19]:
c.expand_as(m)

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [20]:
t = c.expand_as(m)
t.storage()

<ipython-input-20-b579dd4930e5>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  t.storage()


 10.0
 20.0
 30.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [21]:
t.stride(), t.shape

((0, 1), torch.Size([3, 3]))

In [22]:
c = tensor([10., 20, 30])
m = tensor([[1., 2, 3], [4, 5, 6], [7, 8, 9]])
c = c.unsqueeze(1)
m.shape, c.shape

(torch.Size([3, 3]), torch.Size([3, 1]))

In [23]:
c+m

tensor([[11., 12., 13.],
        [24., 25., 26.],
        [37., 38., 39.]])

In [24]:
c = tensor([10., 20, 30])
c.shape, c.unsqueeze(0).shape, c.unsqueeze(1).shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [25]:
c.shape, c[None, :].shape, c[:, None].shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [26]:
def matmul(a, b):
  ar, ac = a.shape
  br, bc = b.shape
  assert ac == br
  c = torch.zeros(ar, bc)
  for i in range(ar):
    c[i] = (a[i].unsqueeze(-1) * b).sum(dim=0)
  return c

%timeit -n 20 t4 = matmul(m1, m2)

207 µs ± 96.3 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


torch.Size([10])

torch.Size([784, 10])